### ISSUE TITLE
What is the BuildInfo for the R1 release image?

### ISSUE THREAD

**Issue by hsakoh** [Linkstar-H-series/Openwrt#3]
### Describe the bug

Is [this image](https://github.com/Linkstar-H-series/Openwrt/releases/tag/v22.03.3) that was recently released built from sources in this repository?

I tried running it, but it is a bit odd. Specifically, as follows.
* When I connect via SSH, the banner is LEDE
![image](https://user-images.githubusercontent.com/20980395/227737176-851aadbf-65f9-428b-9047-b823d1790893.png)
* `uname -a'` results in `Linux OpenWrt 4.19.245-android #0 SMP Fri Mar 24 04:34:05 2023 aarch64 GNU/Linux`

### OpenWrt version

R23.3.23

### OpenWrt target/subtarget

rockchip/armv8

### Device

LinkStar H68K

### Image kind

Official downloaded image

**Comment by coolsnowwolf** [comment]
It's special version build from rockchip's BSP kernel

**Comment by hsakoh** [comment]
@coolsnowwolf 

Is that kernel repository [this](https://github.com/rockchip-linux/kernel)?

I want to know the procedure to build with that kernel and the sources in this repository.

And why is Banner an LEDE?
It doesn't seem to be included in the sources of this repository or in the BSP kernel.

**Comment by coolsnowwolf** [comment]
Due to rockchip's RK3568 RKBIN ( Bootloader) dual boot policy,   boot first from TF card needs BSP uboot and BSP kernel in the image

It would solved what rockchip release their opensource  ATF

**Comment by hsakoh** [comment]
I understand the reason why the self-built image cannot be booted from the TF card,
 as the official images (R22.11.18 or Android TV) and release images (R1) are written to the eMMC.
